openapi: 3.0.3

info:
  title: Stock API
  description: 주식 주문 처리 API
  version: 1.0.0
paths:
  /orders:
    get:
      summary: 주문 목록 조회
      description: 모든 주문을 조회합니다.
      responses:
        '200':
          description: 주문목록 조회 성공
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Order'
  /orders/{order_id}:
    get:
      summary: 특정 주문 처리
      description: 특정 주문 ID에 해당하는 주문정보를 조회
      parameters:
      - name: order_id
        in: path
        required: true
        description: 조회할 주문 ID
        schema:
          type: integer
          example: 123456
      responses:
        '200':
          description: 주문 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
                
components:
  schemas:
    Order:
      type : object
      properties:
        order_id:
          type: integer
          description: 주문 id
          example: 123456
        user_id:
          type: string
          description: 주문자 id
          example: lsj1234
        user_name:
          type: string
          description: 주문자명
          example: 이수진
        stocks:
          type: array
          items :
            $ref: '#/components/schemas/Stock'
              
    Stock:
      type: object
      properties:
        order_date:
          type: string
          description: 주문날짜
          example: "1997-07-16T10:20:30Z"
        updated_date:
          type: string
          description: 주문수정날짜
          example: "1997-07-17T11:20:30Z"
        order_type:
          type: string
          description: 주문타입(매도, 매수)
          enum: [
            "sell",
            "buy"
          ]
          example: "sell"
        stock_code:
          type: string
          description: 주문주식의 코드(티커)
          example: "005930"
        quantity:
          type: integer
          description: 주문량
          example: 20
        price:
          type: integer
          description: 주문가격
          example: 57000
        trading_result:
          type: string
          description: 체결결과(미체결, 체결, 진행중)
          enum: [
            "notconcluded",
            "conclusion",
            "progress"
            ]
          example: "progress"
        trading_date:
          type: string
          description: 체결날짜
          example: "1997-07-17T11:20:30Z"
                  
  