openapi: 3.0.3

info:
  title: Stock API
  description: 주식 주문 처리 API
  version: 1.0.0
paths:
  /orders:
    get:
      summary: 주문 목록 조회
      description: 모든 주문을 조회합니다.
      responses:
        '200':
          description: 주문목록 조회 성공
          content:
            application/json:
              schema:
                type: array
                items :
                  type : object
                  properties:
                    result:
                      type: string
                      description: 주문목록조회 결과 (success)
                    order_id:
                      type: string
                      description: 주문 id
                    user_id:
                      type: string
                      description: 주문자 id
                    user_name:
                      type: string
                      description: 주문자명
                    order_date:
                      type: string
                      description: 주문날짜
                    order_type:
                      type: integer
                      description: 주문타입(0:매도 1:매수)
                    order_stock:
                      type: string
                      description: 주문주식
                    quantity:
                      type: integer
                      description: 주문량
                    price:
                      type: integer
                      description: 주문가격
                    trading_result:
                      type: integer
                      description: 체결결과(0:미체결 1:체결)
                    trading_date:
                      type: string
                      description: 체결날짜
                    
                    
  /orders/{order_id}:
    get:
      summary: 매도 주문 처리
      description: 주문 ID에 해당하는 주문정보를 조회
      parameters:
      - name: order_id
        in: path
        required: true
        description: 조회할 주문 ID
        schema:
          type: string
      responses:
        '200':
          description: 주문 조회 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: 주문 조회 결과 (success)
                  order_id:
                    type: string
                    description: 주문 ID
                  user_id:
                    type: string
                    description: 주문자 ID
                  user_name:
                    type: string
                    description: 주문자명
                  order_date:
                    type: string
                    description: 주문 날짜
                  order_type:
                    type: integer
                    description: 주문 타입
                  order_stock:
                    type: string
                    description: 주문 주식
                  quantity:
                    type: integer
                    description: 주문량
                  price:
                    type: integer
                    description: 주문 가격
                  trading_result:
                    type: integer
                    description: 체결 결과
                  trading_date:
                    type: string
                    description: 체결 날짜
                  
  